### Numpy 기초연습문제

In [4]:
import numpy as np

#### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [6]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [8]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [9]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

#### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [11]:
a[1, 2]

7.0

#### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [13]:
a.shape

(3, 4)

In [14]:
a[[1], :]

array([[5., 6., 7., 8.]])

#### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

In [16]:
a[:,[0, 2]]

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

#### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오bb.

In [18]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [19]:
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

#### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [21]:
b = np.random.random((3, 4))
b

array([[0.56287015, 0.13892601, 0.56645455, 0.47185892],
       [0.66614586, 0.62518892, 0.33448192, 0.38230563],
       [0.76297343, 0.0692463 , 0.96619683, 0.58006459]])

#### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [23]:
c = a * b
c

array([[ 0.56287015,  0.27785201,  1.69936365,  1.88743566],
       [ 3.33072929,  3.7511335 ,  2.34137345,  3.05844501],
       [ 6.86676083,  0.69246299, 10.62816515,  6.96077504]])

#### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [25]:
d = b.T
d

array([[0.56287015, 0.66614586, 0.76297343],
       [0.13892601, 0.62518892, 0.0692463 ],
       [0.56645455, 0.33448192, 0.96619683],
       [0.47185892, 0.38230563, 0.58006459]])

In [33]:
d.shape

(4, 3)

#### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [28]:
print(a.shape, d.shape)

(3, 4) (4, 3)


#### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [30]:
e = a.dot(d)
e

array([[ 4.42752147,  4.44919196,  6.12031486],
       [11.38795993, 12.48168125, 15.63423944],
       [18.3483984 , 20.51417053, 25.14816401]])

#### 12. e에 대하여 각 열의 합을 계산하시오.

In [32]:
np.sum(e, axis=1)

array([14.99702829, 39.50388062, 64.01073294])